name: Generate Snake

on:
  schedule:
    - cron: "0 20 * * *" # Her gün çalışır (UTC 20:00'de)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: MuratGuelr
          outputs: dist/snake.svg

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
